### ISSUE TITLE
Resize very large image fails with blank page

### ISSUE THREAD

**Issue by Maxwell2022** [avalanche123/Imagine#206]
I did perform a test uploading an image of 15MB in my application. The application is then trying to generate a resized version of the original image.

I ended up with a blank page with no error displayed or in the log.

I've tracked it down to this method:

``` php
    /**
     * {@inheritdoc}
     */
    public function load($string)
    {
        $resource = @imagecreatefromstring($string);

        if (!is_resource($resource)) {
            throw new InvalidArgumentException('An image could not be created from the given input');
        }

        return $this->wrap($resource);
    }
```

The error message (after removing the `@`):

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 41260 bytes) in /var/www/test/vendor/imagine/Imagine/lib/Imagine/Gd/Imagine.php on line 133

`@imagecreatefromstring($string);` is crashing without throwing exceptions or error message. I have 256 MB memory allocated for PHP and apparently it's not enough, that's crazy.

If we are not able to fix this issue (and I guess we are not because it's Gd) should we handle the error message a bit better to inform the end user?

**Comment by camburns** [comment]
I've opened an issue in relation to this issue (processing large image files) as there doesn't seem to be any documentation on steps to take when processing large images files.

https://github.com/liip/LiipImagineBundle/issues/711
