### ISSUE TITLE
Imagick and IPTC headers

### ISSUE THREAD

**Issue by gjuric** [avalanche123/Imagine#22]
I know it is not possible to preserve IPTC headers while using the GD adapter, bug Imagick supports this (I guess Gmagick does as well).

It would be nice if resize() could also resize images like THUMBNAIL_INSET does, but maintain IPTC information. And thumbnail() could get rid of the IPTC headers since you probably do not want to increase file size of your thumbnails.

**Comment by naabys** [comment]
If there is an interest for this, I'm currently writing an IPTC Reader (+ a Writer) relying on the `MetadataReaderInterface`. I'd be happy to share (and clean up the code a little to send a PR)
