### ISSUE TITLE
this image gives 'An image could not be created from the given input'

### ISSUE THREAD

**Issue by Abdelhady** [avalanche123/Imagine#233]
I'm using Imagine to resize images after uploading them with curl in /tmp like this:

$_imagine = new \Imagine\Gd\Imagine();
$mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
$image = $_imagine->open($path); // i.e $path = '/tmp/photo.jpg'
// then resizing the $image

It is working fine with any previously uploaded images in my /tmp, but when uploading this image http://newsimg.bbc.co.uk/media/images/67373000/jpg/_67373987_09f1654a-e583-4b5f-bfc4-f05850c6d3ce.jpg then trying to open it with Imagine, it gives the following error:

Fatal error: Uncaught exception 'Imagine\Exception\InvalidArgumentException' with message 'An image could not be created from the given input'

**Comment by nmeri17** [comment]
I think this issue should be reopened. Recently upgraded to php 8, updated packages and suddenly, the GD driver can't read images. When I change it to gmagick as recommended here, it says gmagick not installed. I don't recall installing a GD extension, I don't know how to install a gmagick one and even if I did, I don't expect my users to do so.

I'm currently on the following version of imagine: ~0.5.0

**Comment by mlocati** [comment]
> I'm currently on the following version of imagine: ~0.5.0

The current version is 1.3.2
