### ISSUE TITLE
Saving Transparent PNGs with Imagick driver does not preserve alpha

### ISSUE THREAD

**Issue by andrixh** [avalanche123/Imagine#247]
Hi and thank you for Imagine. This is my very first Github post so please forgive any lack of proper etiquette, resulting from me being inexperienced with contributing to  Open Source.

When I open a full-color PNG with transparency, resize and try to save it, the result is a flattened PNG with black background instead of a transparent one. If oppened on Photoshop, it displays as a background layer, not as a normal layer as it should.

The issue I'm having manifests on the dev branch of imagine, with the imagick driver. This does not happen with the gd driver, and does not happen on the master branch of Imagine with the imagick driver. Also, specifying "flatten"=>false on the save options makes no difference on the result.

**Comment by blurymind** [comment]
still broken

**Comment by Colir** [comment]
still broken too

**Comment by mlocati** [comment]
@Colir do you have a png image and some php code to share that shows this issue?

**Comment by Colir** [comment]
@mlocati please, delete my post, i've just update the lib, and all work great. 
Thank you very much for your fast feedback.
