### ISSUE TITLE
 Call to undefined method Imagick::setColorspace()

### ISSUE THREAD

**Issue by weboAp** [avalanche123/Imagine#258]
receiving error 
 Call to undefined method Imagick::setColorspace()

in vendor/imagine/imagine/lib/Imagine/Imagick/Image.php

at

$this->imagick->setColorspace(static::$colorspaceMapping[$palette->name()]);

line 867

any ideas? Thanks.

**Comment by syrakozz** [comment]
how i can upgrade imageick on centos
