### ISSUE TITLE
[BUG] Convert PNG to JPG with THUMBNAIL_INSET issue

### ISSUE THREAD

**Issue by loonle** [avalanche123/Imagine#283]
I found a bug

when i convert a 800x800 PNG image (user submit, no control over this) to a JPG image which I want it to be 800x800 as well.
I tested with a transparent background PNG. the background appear to be black. 
but as long as the PNG not 800X800 it has nothing wrong.

$image = $imagine->open($targetPng);
$image->thumbnail(new Box(800, 800), ImageInterface::THUMBNAIL_INSET)->save($targetJpg);

And i have tested it with THUMBNAIL_OUTBOUND and i realize it has the same problem is the dimension is the same.

last one. i found out. if i save PNG into jpg using THUMBNAIL_INSET, all the images background turn black.

any idea? btw i found and interesting topic converting png to jpg http://stackoverflow.com/a/12805/805373

UPDATE: I am using GD only

**Comment by cbepxpa3ym** [comment]
Reported 2 years ago, and still no fix. Is it a "dead" project?

**Comment by mlocati** [comment]
Does the source PNG image have a transparent background?

**Comment by mlocati** [comment]
Let me know what's the exact problem... Is this the correct description of the issue?

1. you have a PNG file
2. you resize it, so it has some transparent background
3. you save it as a JPG file
4. the transparent areas are black in the PNG

Is this correct?

**Comment by justim** [comment]
Exact reproduction:

```php
<?php

use Imagine\Image\Box;
use Imagine\Image\ManipulatorInterface;
use Imagine\Imagick\Imagine;

require 'vendor/autoload.php';

$path = './image.png';
$imagine = new Imagine();
$image = $imagine->open($path);

$newSize = new Box(300, 100);
$thumbnail = $image->thumbnail($newSize, ManipulatorInterface::THUMBNAIL_INSET);

$thumbnail->show('jpeg');
```

With the following image:

![image](https://user-images.githubusercontent.com/757292/45757594-0eec1e80-bc24-11e8-8580-1d25f0d6f4d2.png)

If you leave the thumbnail part, the background is white.

**Comment by mlocati** [comment]
So, this is not a bug.
The original PNG image has a transparent background.
When you save it in JPG format (which does not support transparency), Imagick automatically uses black for the background.
We can't do anything to solve this issue...

**Comment by justim** [comment]
The behavior is not consistent, the black background only occurs when you resize it. To use the code from the previous example, but without thumbnailing, the image has a white background:

```php
<?php

use Imagine\Image\Box;
use Imagine\Image\ManipulatorInterface;
use Imagine\Imagick\Imagine;

require 'vendor/autoload.php';

$path = './image.png';
$imagine = new Imagine();
$image = $imagine->open($path);

$image->show('jpeg');
```

The bug is not in the saving part, it seems, but the resize code somewhere adds a black background, or removes the white background.

Either way, to get a white background on a resized transparent PNG is complicated and could be improved (or documented). Not exactly sure how, though.

**Comment by justim** [comment]
Not really a solution, but it might be step in the right direction. Setting the alpha channel to opaque make the background white.

```php
$path = './image.png';
$imagine = new Imagine();
$image = $imagine->open($path);

// setting the alpha channel to opaque make the background white
$image->getImagick()->setImageAlphaChannel(\Imagick::ALPHACHANNEL_OPAQUE);

$newSize = new Box(300, 100);
$thumbnail = $image->thumbnail($newSize, ManipulatorInterface::THUMBNAIL_INSET);

$thumbnail->show('jpeg');
```

FYI, just to thorough, I tried it in plain `\Imagick`, and it also fails:

```php
$path = './image.png';

$imagick = new \Imagick();
$imagick->readImage($path);

// Adding the same line before resizing makes the background white
// $imagick->setImageAlphaChannel(\Imagick::ALPHACHANNEL_OPAQUE);

$imagick->resizeImage(300, 100, \Imagick::FILTER_POINT, 1);

$imagick->setImageFormat('jpeg');
header('Content-Type: image/jpeg');
echo $imagick->getImagesBlob();
```

**Comment by mlocati** [comment]
Yes, Imagine is not involved at all in this bug. Thanks for the deep investigation, @justim: it confirms my results.

I'm going to submit an issue to https://github.com/mkoppanen/imagick.
@justim Can I use [your sample image](https://user-images.githubusercontent.com/757292/45757594-0eec1e80-bc24-11e8-8580-1d25f0d6f4d2.png) in that post I'm going to write?

**Comment by justim** [comment]
Yes, you can.

**Comment by mlocati** [comment]
Here it is: https://github.com/mkoppanen/imagick/issues/253

**Comment by mlocati** [comment]
It turned out it's a problem of `ImageMagick` (the library used by the `imagick` PHP extension).

Here's my (other) submitted issue: https://github.com/ImageMagick/ImageMagick/issues/1400

**Comment by mlocati** [comment]
ImageMagick maintainers say that this is the expected behaviour.
So, when saving an image that support transparency (like PNG) as an image that does not support transparency (like JPG), you should remove the trasparency.

This could be done with the Imagine API with some code like this:

```php
use Imagine\Image\Box;
use Imagine\Image\Palette\RGB;
use Imagine\Image\Point;
use Imagine\Imagick\Imagine;

$imagine = new Imagine();
$inputImage = $imagine->open('./input.png');
$inputImage->resize(new Box(300, 100));
$palette = new RGB();
$finalImage = $imagine->create($inputImage->getSize(), $palette->color('ffffff'));
$finalImage->paste($inputImage, new Point(0, 0));
$finalImage->save('./output.jpg');
```

For Imagick, you can also work directly on the underlying Imagick object:

```php
use Imagick;
use Imagine\Image\Box;
use Imagine\Imagick\Imagine;

$imagine = new Imagine();

$image = $imagine->open('./input.png');
$image->resize(new Box(300, 100));
$image->getImagick()->setImageBackgroundColor('white');
$image->getImagick()->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
$image->save('./output.jpg');

```
