### ISSUE TITLE
Best practice question: centering text at point

### ISSUE THREAD

**Issue by pbowyer** [avalanche123/Imagine#285]
## Background

While creating a charting library I added a method to `Imagine\Imagick\Drawer` to approximately center text on the given point. It's a minor modification of `text()`:

``` php
<?php
// ...
    public function textCenterAtPoint($string, AbstractFont $font, PointInterface $position, $angle = 0)
    {
        try {
            $pixel = $this->getColor($font->getColor());
            $text  = new \ImagickDraw();

            $text->setFont($font->getFile());
            /**
             * @see http://www.php.net/manual/en/imagick.queryfontmetrics.php#101027
             *
             * ensure font resolution is the same as GD's hard-coded 96
             */
            if (version_compare(phpversion("imagick"), "3.0.2", ">=")) {
                $text->setResolution(96, 96);
                $text->setFontSize($font->getSize());
            } else {
                $text->setFontSize((int) ($font->getSize() * (96 / 72)));
            }
            $text->setFillColor($pixel);
            $text->setTextAntialias(true);

            $info = $this->imagick->queryFontMetrics($text, $string);

            $rad  = deg2rad($angle);
            $cos  = cos($rad);
            $sin  = sin($rad);

            // round(0 * $cos - 0 * $sin)
            $x1 = 0;
            $x2 = round($info['characterWidth'] * $cos - $info['characterHeight'] * $sin);
            // round(0 * $sin + 0 * $cos)
            $y1 = 0;
            $y2 = round($info['characterWidth'] * $sin + $info['characterHeight'] * $cos);

            $xdiff = 0 - min($x1, $x2);
            $ydiff = 0 - min($y1, $y2);

            // Start modifications
            $xcharwidth = round(($info['boundingBox']['x2'] - $info['boundingBox']['x1'])/2) -1;
            $ycharwidth = round(($info['characterHeight'])/2);

            $this->imagick->annotateImage(
                $text, $position->getX() + $x1 + $xdiff - $xcharwidth,
              $position->getY() + $y2 + $ydiff - $ycharwidth, $angle, $string
            );

            $pixel->clear();
            $pixel->destroy();

            $text->clear();
            $text->destroy();
        } catch (\ImagickException $e) {
            throw new RuntimeException(
                'Draw text operation failed', $e->getCode(), $e
            );
        }

        return $this;
    }
```

Obviously I don't want to keep my dirty hack of modifying the core Imagine files, and I'm looking for advice on the best place to implement methods which need access to the core image library provider (Imagick in this case) when using Imagine.
### Thought 1: Subclass Imagine\Imagick\Drawer and add a method

Not possible as Imagine declares the classes as `final`. I understand why and suspect I use the library in a different way to that expected...
### Thought 2: Adjust the point location in my own code

This would be ok... if I could get hold of `$this->imagick` from my Drawer instance so I can call `queryFontMetrics()`. Without getting hold of the imagick instance I have to do a fair amount of duplicate setup in my code, creating another Imagick instance etc.
### Any others?

Imagine must be extendible, I'm just at a loss how to do it. I'd like to learn and discover something new which will make me a better programmer. Thanks!

**Comment by scuben** [comment]
Hi @pbowyer, I stood in front of the very same problem today. I found the method `box` from `AbstractFont` which returns a `Box` object containing the `width`. With that information I could position my top/left Position accordingly.

**Comment by syxchina** [comment]
$tf = $imagine->font($fontfile, 100, $image->palette()->color('#fff'));
$size = $tf->box($text);

$site's width is right!
