### ISSUE TITLE
Gmagick profile conversion error

### ISSUE THREAD

**Issue by oo12** [avalanche123/Imagine#302]
I've come across a problem converting CMYK images to RGB using the Gmagick driver: ```$image->usePalette(new Imagine\Image\Palette\RGB());```
The source images have embedded CMYK profiles.

This [line](https://github.com/avalanche123/Imagine/blob/e995843d150fdbe905600509656a546a931372ab/lib/Imagine/Gmagick/Image.php#L693) throws an exception: _LCMS encoding not enabled_.
Changing 'ICM' to 'icc' fixes it.  I noticed the Imagick driver also uses ['icc'](https://github.com/avalanche123/Imagine/blob/e995843d150fdbe905600509656a546a931372ab/lib/Imagine/Imagick/Image.php#L693).
Is there a reason to use ICM on Gmagick but icc on Imagick?  The [documentation](http://us2.php.net/manual/en/gmagick.profileimage.php) for Gmagick::profileimage() doesn't list 'ICM' as a valid name.

ICC and ICM profiles are the same thing; the .icm extension is specific to Windows.

OS X 10.9.2
PHP 5.5.10
gmagick 1.1.7RC2
GraphicsMagick 1.3.19 2013-12-31 Q8
(--with-lcms=no --with-lcms2=yes)

**Comment by romainneutron** [comment]
Hello,

I just bumped into your issue. 'ICM' is the correct value. Your issue occurs when graphicsmagick is not compiled with lcms2.

You shoulp recompile it with the option `--with-lcms2`

I'm adding some words about this in the exception message.
