### ISSUE TITLE
::save() transparent PNG to JPG results in black background

### ISSUE THREAD

**Issue by ItsReddi** [avalanche123/Imagine#322]
following issue:
https://github.com/yiisoft/yii2/issues/3253

maybe related to:
#283 ?

**Comment by ItsReddi** [comment]
https://github.com/yiisoft/yii2/issues/6014

**Comment by cbepxpa3ym** [comment]
Reported 2 years ago and still nothing.. This project is dead. It is sad Yii team used it to code the core yii2_imagine extension.

**Comment by mlocati** [comment]
This can be closed, right?
