### ISSUE TITLE
Strip sets default color profile and fails sometimes

### ISSUE THREAD

**Issue by scoolen** [avalanche123/Imagine#353]
Since 19 July 2013 [Imagine\Imagick\Image::strip()](https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Imagick/Image.php#L172) sets a default profile.

We recently switched to v0.6.0 and, since then, we're running into exceptions related to color profiles every now and again:

```
Unable to add profile sRGB_IEC61966-2-1_black_scaled.icc to image
Stack trace:
#0 /[...]/vendor/imagine/imagine/lib/Imagine/Imagick/Image.php(172): 
Imagine\Imagick\Image->profile(Object(Imagine\Image\Profile))
```

According to the PHP documentation strip _"strips an image of all profiles and comments"_. So why is a default profile set first?

Example image that gave problems:
![Seal for yourselves](http://i.imgur.com/fGtHEnw.jpg)

**Comment by xiaolongchen** [comment]
There is a similar problem in lib/Imagine/Imagick/Image.php
$this->imagick->profileImage('icc', $profile->data());
which triggers the same error:
Unable to add profile sRGB_IEC61966-2-1_black_scaled.icc to image
I tried to comment the throw and it seems to work.
Could you have a look please?

**Comment by trsteel88** [comment]
I am receiving the same error as @xiaolongchen in lib/Imagine/Imagick/Image.php (line 622).

Running php 7.1
