### ISSUE TITLE
Imagine\Gd\Drawler::text() — problems with "fitted" text.

### ISSUE THREAD

**Issue by vlad-light** [avalanche123/Imagine#364]
Hello, I'm currently playing around with Imagine. So I decided to create an simple image-placeholder service... The user may pass a text-string which will be centered and added to the image. 
Consider following example:

``` php
//create required instances...
$Imagine = new \Imagine\Gd\Imagine();
$Palette = new \Imagine\Image\Palette\RGB();
//Background color of the upcomming image basend on settings passed by user...
$BackgroundColor = $Palette->color($settings['background_color'], 0);
//...some other code...
$TextColor = $Palette->color($settings['text_color'], 100);
//create an ImageBox for upcomming image based on given width and height
$ImageBox = new \Imagine\Image\Box($settings['width'], $settings['height']);
//get center X|Y coordinates for ImageBox
$ImageCenterPosition = new \Imagine\Image\Point\Center($ImageBox);
//create Text Object with font-family, font-size and color from settgins
$TextFont = new \Imagine\Gd\Font( $settings['font_file'] , $settings['font_size'],  $TextColor);
//create a Box (dimensions) based on font and given string...
$TextBox = $TextFont->box( $settings['text'] );
//get center X|Y coordinates for the box containing the text
$TextCenterPosition = new \Imagine\Image\Point\Center( $TextBox );
//calculate center X|Y coordanates from ImageBox center coordanates and FontBox center coordanates
$CenteredTextPosition = new \Imagine\Image\Point( $ImageCenterPosition->getX() - $TextCenterPosition->getX(), $ImageCenterPosition->getY() - $TextCenterPosition->getY());
//create an image with ImageBox dimensions and BackgroundColor
$_img_ = $Imagine->create($ImageBox, $BackgroundColor);
//now draw the text...
$_img_->draw()->text($settings['text'], $TextFont, $CenteredTextPosition);
```

this code works well (see list of cases and screens), untill I try to use `$width` param within a `draw()` method.
##### 1st case:

with following user settings creates — [Screenshot #1](https://cloud.githubusercontent.com/assets/277235/4243354/803523b0-3a0b-11e4-909d-ead87983c2ef.PNG) :ok_hand:

``` php
$settings['width'] = $settings['height'] = 600;
$settings['text'] = "some very long";
```

---
##### 2nd case:

with following user settings creates — [Screenshot #2](https://cloud.githubusercontent.com/assets/277235/4243353/802e2736-3a0b-11e4-81b7-171f46c322bf.PNG) :ok_hand:

``` php
//width and height are the same...
$settings['text'] = "some very long textttttttttttttt"; //
```

---
##### 3rd case:

with following user settings creates — [Screenshot #3](https://cloud.githubusercontent.com/assets/277235/4243352/802c36c4-3a0b-11e4-9698-c32126b4aa1f.PNG)  :ok_hand:

``` php
//width and height are the same...
$settings['text'] = "some very long\ntextttttttttttttt"; //manual LineBreak
```

---
##### 4th case: WRONG POSITIONING

with following user settings creates — [Screenshot #4](https://cloud.githubusercontent.com/assets/277235/4243351/802b240a-3a0b-11e4-947f-6556603b45bc.PNG) :thumbsdown:

``` php
//width and height are the same...
$settings['text'] = "some very long textttttttttttttt"; //long text
//...some other code...
//now draw the text AND SET the $width param to 450, so line breaks will be created automatically...
$_img_->draw()->text($settings['text'], $TextFont, $CenteredTextPosition, 0, 450); //NOW POSITIONING GOES WRONG !!!
```

---

So by using `$width` param possible linebreaks are generated _automaticaly_ so the `box( "string" )` of the text _with linebreaks_ may differ from original one . 
`text()` method uses `$this->wrapText()` but unfortunetelly it's  a `private` method

Any suggestions ?!

**UPDATE**

I think a quick-solution would be a `$width` param for `Font->box()` method. This way I could get _a correct_ dimensions

**Comment by mlocati** [comment]
In #671 I added a new method to the Font objects so that you can split a text into multiple lines so that it fits a specific width.
