### ISSUE TITLE
Thumbnail transparency issue PNG to JPG

### ISSUE THREAD

**Issue by PommeVerte** [avalanche123/Imagine#398]
Hello,
When taking a PNG with transparency and making a jpg thumbnail from it there are weird artifacts around the edges.
Bellow is an example:

``` php
$imagine = new \Imagine\Imagick\Imagine();

$size = new \Imagine\Image\Box(1920, 1080);
$mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;

$imagine->open('inputFile.png')
        ->thumbnail($size, $mode)
        ->save('outputFile.jpg');
```

![image](https://camo.githubusercontent.com/455638c5e011cf6e66c32b3bfda62f2239a912c8/687474703a2f2f7777772e74696e6b6572706f702e636f6d2f646f63732f63757272656e742f696d616765732f6772656d6c696e2d68696e64752e706e67)

Truns into :

![image](https://cloud.githubusercontent.com/assets/1415875/5233535/be9cf788-7758-11e4-987b-7fb668ab7e91.png)

I've tried different filters. No dice. Any clues would be great. I wouldn't mind making a pull request if I had even a remote idea of what was causing this.

```
php5-imagick : 3.1.2-1build1
libmagickcore5 : 8:6.7.7.10-6ubuntu3
libmagickwand5 : 8:6.7.7.10-6ubuntu3
```

**Comment by mlocati** [comment]
We'd need the original source image.
If you still have it feel free to reopen this issue.
