### ISSUE TITLE
Compatibility with PHPUnit

### ISSUE THREAD

**Issue by witrin** [avalanche123/Imagine#399]
I get the following run-time notice in TYPO3 Flow using Imagine 0.6.2:

```
Declaration of Imagine\Test\Constraint\IsImageEqual::evaluate() should be compatible with 
PHPUnit_Framework_Constraint::evaluate($other, $description = '', $returnResult = false)
```

Should be easy to fix by just adding `, $description = '', $returnResult = false`. Or did I miss something?

**Comment by beechit** [comment]
this issue still exists or is this my bad ?

**Comment by witrin** [comment]
Sorry haven't found the time for this, so yes :).

**Comment by mlocati** [comment]
This issue have been ready fixed.
