### ISSUE TITLE
Suggestion: add a function to load the 'best' library available, Gmagick > Imagick > GD2.

### ISSUE THREAD

**Issue by twicejr** [avalanche123/Imagine#400]
Something like $imagine = \Imagine\Instance::getBest(); would be neat. 

Although it is of course not much work to implement manually in a project.

**Comment by mlocati** [comment]
What's the best library? GD is faster: is it the best one? Imagick is more powerful: is it the best one?
I think that the best one depends on the specific library usage, so I'd leave this detection to the app using Imagine.
