### ISSUE TITLE
Metadata read should not (?) throw an exception if exif extension is not present.

### ISSUE THREAD

**Issue by makasim** [avalanche123/Imagine#403]
I think the metadata should be access if there is a possibility to do so, for example a user has a exif extension. If not it has to do just nothing. Right now people able to use LiipImagineBundle if they do not have exif extension cuz of this exception: https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/Metadata/ExifMetadataReader.php#L25

For referance: https://github.com/liip/LiipImagineBundle/issues/501

**Comment by martijn80** [comment]
Hi @makasim i think you meant to say : Right now people ARE NOT able to use LiipImagineBundle if they do not have exif extension cuz of this exception.

**Comment by martijn80** [comment]
What i did to fix this : 
1. Remove the constructor from the file you referenced
2. Add this if to the top of the extract function at the bottom of the referenced file
```
private function extract($path)
{
    if ( function_exists('exif_read_data') == false)
    {
        return array();
    }
... rest of the code unchanged
```
I have no experience in making a PR or running any of the tests, so maybe someone else could be so kind to do this maybe?

**Comment by x3r0z** [comment]
I fixed that problem change the line 64 in imagine.xml in ImagineBundle, change the value of the parameter liip_imagine.meta_data.reader.class, by default is Imagine\Image\Metadata\ExifMetadataReader and I change to Imagine\Image\Metadata\DefaultMetadataReader

**Comment by mlocati** [comment]
Recent versions of Imagine already implements it (see https://github.com/php-imagine/Imagine/blob/1.2.4/src/Factory/ClassFactory.php#L33)
