### ISSUE TITLE
grayscale effect is very slow

### ISSUE THREAD

**Issue by onigoetz** [avalanche123/Imagine#404]
Hi,

I'm trying to use the grayscale filter but I see it's very slow, (close to 2 minutes for a 500x500 image)

Is it possible to make the use of `imagefilter($resource, IMG_FILTER_GRAYSCALE)` in the GD version and fallback to how the filter handles the transformation when it isn't available ?

If you're okay with the idea, I can make a pull request.

**Comment by mlocati** [comment]
Recent Imagine versions use imagefilter + IMG_FILTER_GRAYSCALE
