### ISSUE TITLE
Add cache options to Imagine

### ISSUE THREAD

**Issue by mbrostami** [avalanche123/Imagine#412]
Hi,  
Thanks for great tool Imagine.  
You can add cache options to Imagine for better resource management, I done this by caching an image with multiple sizes if user request them. For example an image has a URL like this :   
//domain.com/images.php/100x100/hello.jpg  
I have a web page with 100 images on it. So if I don't cache images, it will take more resources(RAM, CPU ...). 
Thanks again.

**Comment by romainneutron** [comment]
This cache should be developed outside imagine, not in Imagine iself
