### ISSUE TITLE
fopen vs curl for external images

### ISSUE THREAD

**Issue by glend** [avalanche123/Imagine#415]
Most shared hosting providers disable the setting allow_furl_open, therefore you can't fetch external images. There are ways to override this setting in certain providers but they highly discourage it because of security issues?

Why not use curl instead?

**Comment by romainneutron** [comment]
I'd gladly appreciate we refactor this part of the app to allow such feature, but it's not on the roadmap

**Comment by mlocati** [comment]
Implemented in #607
