### ISSUE TITLE
Thumbnail sometimes return 500 on low resolution images

### ISSUE THREAD

**Issue by bluescreen** [avalanche123/Imagine#422]
The ->thumbnail() method sometimes return a 500 error when using a low resolution image with jpeg_quality less than 80. I think it should throw an exception instead of 500 error.

$this->imageProcessor
                ->open($src)
                ->thumbnail(new Box($width, $height), ImageInterface::THUMBNAIL_INSET)
                ->save( $dest)
                ->show("jpeg", ['jpeg_quality' => 90]);

**Comment by Fedik** [comment]
I suppose you mean Server Error 500, 
such often happen when the source image have a big resolution, and you tried resize it using "PHP GD",

as possible solution you need to install "PHP Imagic" extension on your server, 
or order a loot more server RAM for prevent "PHP GD" crash  :wink:

The Imagine library cannot fix this :smile:

**Comment by romainneutron** [comment]
Agreed with @Fedik 

Without a stacktrace, I can't do anything. Please reopen with a stackstrace
