### ISSUE TITLE
RuntimeException: Save operation failed on AWS S3 Url

### ISSUE THREAD

**Issue by ajeetvarma** [avalanche123/Imagine#423]
I have implemented https://github.com/avalanche123/Imagine in a symfony2 project and it is working fine on local folder but when i m trying to generate thumbnail on s3 storage url it is not working and give following error message 

          "RuntimeException: Save operation failed" . 

my s3 upload code is as below : 

          private function upload_image($temp_file,$FilePath,$file_type){
          $awsKey = $this->getContainer()->getParameter("AWS_ACCESS_KEY");
          $awsSecretKey = $this->getContainer()->getParameter("AWS_SECRET_KEY");
          $bucket = $this->getContainer()->getParameter('bucket');

         $s3 = new S3($awsKey, $awsSecretKey);
         $k = $s3->putObjectFile($temp_file, $bucket, $FilePath, S3::ACL_PUBLIC_READ, array());
         return $k;
         }

And thumbnail create action is : 

          function createThumbnail($entity, $sectionName){
                   $em = $this->getContainer()->get('doctrine.orm.entity_manager');
                   $imagine = new \Imagine\Gd\Imagine();
                   $imageInfosQuery = $em->createQuery("SELECT i FROM EntityBundle:ImageInfo i WHERE  i.resourceName= :resource_name AND i.resourceId= :resource_id ");
                  $imageInfosQuery->setParameter(':resource_name', $sectionName);
                  $imageInfosQuery->setParameter(':resource_id', $entity->getId());
                  $imageInfos = $imageInfosQuery->getResult();
                  foreach($imageInfos as $imageInfo){
                           if(isset($imageInfo)){
                          $imageP = $imageInfo->getImage();
                          $imageUploadingRootDirectory = $this->getContainer()->getParameter('S3_URL');
                          $imageAbsoulutePath = $imageUploadingRootDirectory."uploads/".$imageP->getName();
                          $image = $imagine->open($imageAbsoulutePath);
                          $parameters = $this->getContainer()->getParameter("image_thumb");
                          foreach($parameters as $parameter){
                          if(is_dir($imageUploadingRootDirectory."uploads/".$parameter."/") == false){
                                          mkdir($imageUploadingRootDirectory."uploads/".$parameter."/", 0777);
                              }
                              $size    = new \Imagine\Image\Box($parameter, $parameter);
                                try{
                                      $image->thumbnail($size)- >save($imageUploadingRootDirectory."uploads/".$parameter."/".$imageP->getName());
                                     } catch(Exception $e) {
                                           echo $e;
                                      }
                                   }    
                                  }
                              }
                           }

And parameter.yml is : 

          parameters:
                      database_driver: pdo_mysql
                      database_host: 127.0.0.1
                      database_port: null
                      database_name: ######
                      database_user: #####
                      database_password: ######
                      mailer_transport: gmail
                      mailer_host: smtp.gmail.com
                      mailer_user: ########
                     mailer_password: #######
                     locale: en
                     secret: ThisTokenIsNotSoSecretChangeIt
                     image_thumb: { THUMB_40: 40, THUMB_150: 150, THUMB_270: 270, THUMB_400: 400, THUMB_570: 570, THUMB_1200: 1200 }
                     aws_access_key: AWS_KEY
                     aws_secret_key: AWS_SECRET_KEY

                       S3_URL: https://s3-ap-southeast-1.amazonaws.com/#####-dev/
                       bucket: ######-dev

I am unable to understand exact problem . please suggest me what i should do .

Thanks in Advance ...

**Comment by romainneutron** [comment]
It seems GD does not support this stream wrapper, you can either try to dump you data locally then copy it, otherwise write the result of the ImageInterface::get method
