### ISSUE TITLE
Feature: Get image orientation?

### ISSUE THREAD

**Issue by burzum** [avalanche123/Imagine#427]
I've got the task to auto-rotate images and I've been surprised the Imagine lib doesn't come with a method to get the orientation from the image object? You need to orientation before you can auto-rotate it to whatever is desired.

I could implement that feature - if it is desired at all. I prefer to ask before wasting my time on this. So please let me know if we want this in Imagine or not.

By looking at the Image classes I haven't seen a way to get the original image file path. This is something else the image object should preserve IMHO.

I know there are engine specific functions but if the path would be still available, I could simply apply this for all images:

```php
	public static function getImageOrientation($imageFile) {
		if (!file_exists($imageFile)) {
			throw new \RuntimeException(sprintf('File %s not found!', $imageFile));
		}
		$exif = exif_read_data($imageFile);
		if ($exif === false) {
			return false;
		}
		if (!empty($exif['Orientation'])) {
			switch ($exif['Orientation']) {
				case 0:
					$angle = 0;
					break;
				case 3:
					$angle = 180;
					break;
				case 6:
					$angle = -90;
					break;
				case 8:
					$angle = 90;
					break;
				default:
					$angle = 0;
					break;
			}
		}
		return $angle;
	}
```

**Comment by romainneutron** [comment]
It's possible with current version:

```
$image = $imagine
    ->setMetadataReader(new DefaultMetadataReader())
    ->open('chenille.jpg');
$metadata = $image->metadata();
$orientation = $metadata['exif.Orientation'];
```

**Comment by burzum** [comment]
Thank you I haven't noticed that, is it even in the documentation?

Also, how reliable is `$metadata['exif.Orientation'];`? Is it using exif_read_data() as well?

**Comment by romainneutron** [comment]
Yep, and it's implemented here https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/Metadata/ExifMetadataReader.php

**Comment by burzum** [comment]
Great, thanks again! :+1:
