### ISSUE TITLE
Manipulator interface return type

### ISSUE THREAD

**Issue by gsouf** [avalanche123/Imagine#428]
Before doing any PR can we replace the ``@return ManipulatorInterface`` annotation with ``@return ImageInterface`` (it already implements ImageManipulator)  in the following file : https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/ManipulatorInterface.php#L32 ?
Because it causes problems with Ide. For instance when we do : 

```php
$image->thumbnail(...)->getSize();
```

The ide cant find the method ``getSize``

**Comment by romainneutron** [comment]
Hello,

doing this would be wrong: the class `Imagine\Filter\Transformation` returns a ManipulatorInterface, not an ImageInterface.

However, I've proposed a patch that solve your issue here https://github.com/avalanche123/Imagine/pull/429

**Comment by gsouf** [comment]
Hello,

I like this patch !
