### ISSUE TITLE
Trying to render svg to transparent background png

### ISSUE THREAD

**Issue by crazycodr** [avalanche123/Imagine#442]
I tried a few different ways but can never get the SVG to open with a transparent background and all my PNGs end up with a background when they should not. Is there a way to achieve this with imagine?

```PHP
        $im = new Imagick();
        $im->setBackgroundColor(new ImagickPixel('transparent'));
        $im->readImage($sourcedir . $vector);
        $im->adaptiveresizeimage($dpi * $size, $dpi * $size);
        $im->setImageFormat("png32");
        file_put_contents(
            __DIR__ . '/../../graphics/rendered-objects/components/' . basename(
                $vector,
                '.' . $vector->getExtension()
            ) . '-' . $suffix . '.png',
            $im
        );
```

**Comment by PommeVerte** [comment]
Same. For some reason I got this working at one point but can't for the life of me figure out how. When using HHVM for instance the svgs will show transparent but then colorizing just screws everything up.

**Comment by PommeVerte** [comment]
There may be a way of using masks to accomplish this so long as your svg isn't too complex. Since I only deal with black on transparent SVGs the following works:

```php
$imagine = new Imagine();
$image = $imagine->open('path/to/svg');
$image->applyMask($image->mask()); // this makes it so the white BG becomes transparent.
```

**Comment by crazycodr** [comment]
I ended up using PhantomJS + NodeJS to do what i needed. Could never find out a good workaround!
