### ISSUE TITLE
Imagick resource limits

### ISSUE THREAD

**Issue by vchrm** [avalanche123/Imagine#463]
Since Image Magick is multithreaded by default, our thumbnails are on our 16-CPU server generated pretty quickly. However, it consumes all of our CPU cores, so when images are being uploaded and processed, rest of our application does not feel very good about it.

Image Magick does come with functionality to limit its resource usage:
http://php.net/manual/en/imagick.getresourcelimit.php

My question is: How to implement this functionality to Imagine? I understand that this is specific just for Imagick backend. If I wanted to implement this to Imagine, what would be the best way?

I was thinkink about passing some parameter to Imagine\Imagick\Imagine::__construct().

**Comment by Danack** [comment]
Speaking as the maintainer of Imagick....

> If I wanted to implement this to Imagine, what would be the best way?

This is something your sysadmins can set through the ImageMagick policy.xml file. That is probably the best way to set it, in a standard way across servers.

Additionally:

i) I don't recommend using the multi-threading capabilities of OpenMP with ImageMagick - it doesn't seem completely stable.

ii) I don't recommend running Imagick in PHP code that is part of a web-server. It is much better to run image conversion as a background task, through something like supervisord, with an appropriate number of worker threads.

Doing those two things would mean that image conversion doesn't use an inappropriate number of resources.
