### ISSUE TITLE
Best fit

### ISSUE THREAD

**Issue by zhukovsergey** [avalanche123/Imagine#465]
Hello!
How can I do **limit** on _width_ or _height_ picture?
For Example: in **SimpleImage** unofficial extension has **best_fit($max_width, $max_height)** method:

```
$img = new SimpleImage($pathThumb);
$img->best_fit(1280, 768)->save($pathThumb);
```

Accordingly, if one of the parties will be more, image will resize proportional.

**Comment by gabrielkaputa** [comment]
Hi,

https://imagine.readthedocs.org/en/latest/ THUMBNAIL_INSET is what you are looking for.
