### ISSUE TITLE
$image->paste with large watermark

### ISSUE THREAD

**Issue by skazhikadyadya** [avalanche123/Imagine#471]
Hi. How I can use paste method if I have watermark image size, for example 200x200 and $image is 150x150? Can I place watermark into center of image? Thanks.

**Comment by everbslab** [comment]
You have to scale the watermark since source image bounds with size of watermark.

$size      = $image->getSize();
$wSize     = $watermark->getSize();

        if($size->getWidth() - $wSize->getWidth() <= 0 || $size->getHeight() - $wSize->getHeight() <= 0) {
            $watermark->resize(new Imagine\Image\Box($size->getWidth()/2, $size->getHeight()/2));
        }

        $centerImage = new Imagine\Image\Point\Center(new Imagine\Image\Box($pointX, $pointY));

        $image->paste($watermark, $centerImage);

**Comment by skazhikadyadya** [comment]
Thank you, it works fine!
