### ISSUE TITLE
Possible typo in searchdoc.js

### ISSUE THREAD

**Issue by jones6951** [avalanche123/Imagine#482]
I was playing with a code static analysis tool today, which highlighted a possible typo in searchdoc.js. I'm not familiar enough with this project (it was linked from some other yii2 project) but figured I'd ask here in case it is a problem and someone wants to fix it.

Anyway, the file was Imagine/docs/API/API/js/searchdoc.js, line 117
            _this.moveTimout = setTimeout(go, 100);

Should this be _this.moveTimeout, rather than Timout?

**Comment by romainneutron** [comment]
This code is auto generated by sphinx :) no worries
