### ISSUE TITLE
GD driver does not handle well transparency in PNG images

### ISSUE THREAD

**Issue by Taluu** [avalanche123/Imagine#498]
Using Imagick, the transparency of png images is handled correctly, but as I have memory usage problem (which are not present when using GD), I have to use GD. But the resulting images (which are thumbnails of another image) has a black background instead of transparent background, in png format.

Raw png :
![51](https://cloud.githubusercontent.com/assets/239685/15497905/44a6f898-219d-11e6-91f1-2949f4de87d1.png)

Imagick Result :
![51-thumb](https://cloud.githubusercontent.com/assets/239685/15505326/57f36c4e-21c3-11e6-8ccb-245deab83cbd.png)

GD Result :
![51](https://cloud.githubusercontent.com/assets/239685/15497865/177646b2-219d-11e6-9650-90b4a9cd3270.png)

Code used :

``` php
#!/usr/bin/env php
<?php
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;

use Imagine\Gd\Imagine as GdDriver;
use Imagine\Imagick\Imagine as ImagickDriver;

require __DIR__ . '/vendor/autoload.php';

const THUMB_WIDTH = 640;
const THUMB_HEIGHT = 480;
const RESOLUTION = 200;
const RAW = __DIR__ . '/raw.png';

$imagine = [
    'gd' => new GdDriver,
    'imagick' => new ImagickDriver
];

$options = [
    'format' => 'png',
    'png_compression_level' => 0,

    'resolution-units' => ImageInterface::RESOLUTION_PIXELSPERINCH,
    'resolution-x' => RESOLUTION,
    'resolution-y' => RESOLUTION
];

foreach ($imagine as $name => $driver) {
    $slide = $driver->open(RAW);

    $path = sprintf('%s/thumb-%s.png', dirname(RAW), $name);

    $thumbed = $slide->thumbnail(new Box(THUMB_WIDTH, THUMB_HEIGHT));
    $thumbed->save($path, $options); // do not alter quality
}

return 0;
```

**Comment by alpharder** [comment]
👍

**Comment by Destroy666x** [comment]
Is there any update on this issue?

**Comment by mlocati** [comment]
https://github.com/avalanche123/Imagine/pull/585 should fix this issue

**Comment by minitauros** [comment]
I am having the same issue, but even with the Imagick driver transparency isn't handled in my image. Any news on when the proposed solution will be - if - implemented?

**Comment by mlocati** [comment]
@minitauros could you check if #585 fixes your issue?

**Comment by minitauros** [comment]
@mlocati I can, but how do I check out this branch within my composer packages? Or how do I pull in this branch at all? I'm quite familiair with git and github, but this would be the first time testing someone else's branch inside a composer installed package :].

**Comment by mlocati** [comment]
The simplest and fastest solution is to download the zip archive of my branch from https://github.com/mlocati/Imagine/archive/fix-loading-indexed-png.zip

**Comment by minitauros** [comment]
The method you described works :). For the rest I have some disappointing information. Either my memory is failing me, or I have not tested my case correctly before filing the issue above. The image that I thought had a transparent background, apparently didn't have a transparent background to begin with. I have tested displaying another image **with** a transparent background, and it works with both your library and the original one. For now I do not have any further information, so please consider my issue irrelevant for now.

**Comment by minitauros** [comment]
Sorry, I will rephrase what I said. I thought that the library was broken, but it now seems that it was my own fault, because the image I had been testing with appears to have a non-transparent background anyway, meaning there was no transparency to test.

To perform some testing anyway, I have loaded a different image _with_ a transparent background. Both the current version of the library and your PR ha ndle the transparency well, in my case (with the GD driver).

Therefore you can consider my issue/comment/remark irrelevant.
