### ISSUE TITLE
No error reporting during out-of-memory crash due to use of @ at sign error control operator

### ISSUE THREAD

**Issue by mh3720** [avalanche123/Imagine#499]
`lib/Imagine/Gd/Imagine.php`

In `function open()`:

```
$resource = @imagecreatefromstring($data);
```

If this causes an out-of-memory crash ("Fatal error: Allowed memory size of xxx bytes exhausted"), the error will not be reported or displayed anywhere, because the @ at sign error control operator suppresses the error.

This may occur when trying to open large image files.

Using the @ at sign here makes a simple problem very hard to debug.  I don't see any good reason to use the @ sign in this situation.  Please remove the @ at sign.

Thanks in advance.

**Comment by xorus** [comment]
+1

Also, errors like "imagecreatefromstring(): gd-png: fatal libpng error: Read Error: truncated data in ..." are not being reported nor handled, and that also stops the script execution.

**Comment by mlocati** [comment]
I don't think there's a way to continue the PHP script execution once PHP runs out of memory... I'm going to close this issue because of that, but feel absolutely free to reopen it if you are aware of any solution.
