### ISSUE TITLE
in yii2 Imagine0.5 version use gmagick  throw 'alpha transparency not implemented'

### ISSUE THREAD

**Issue by cnzhangxl** [avalanche123/Imagine#509]
now my code is:
      /_if ($color->getAlpha() > 0) {
                // TODO: implement support for transparent background
                throw new RuntimeException('alpha transparency not implemented');
       }_/
I can do that right？

**Comment by burzum** [comment]
Can you please try Imagine 6.3 and tell me if it works?

**Comment by mlocati** [comment]
Closing because of lack of feedback (and Imagine should have this fixed).
