### ISSUE TITLE
Undefined constant Imagick::IMGTYPE_TRUECOLORMATTE with ImageMagick 7.0.x

### ISSUE THREAD

**Issue by kvbogdanov** [avalanche123/Imagine#524]
Got this error while usin' Imagine as an Yii2 component.

in /imagine/lib/Imagine/Imagick/Image.php at line 815

     * @throws InvalidArgumentException
     */
    private function setColorspace(PaletteInterface $palette)
    {
        static $typeMapping = array(
            // We use Matte variants to preserve alpha
            PaletteInterface::PALETTE_CMYK      => \Imagick::IMGTYPE_TRUECOLORMATTE,
            PaletteInterface::PALETTE_RGB       => \Imagick::IMGTYPE_TRUECOLORMATTE,
            PaletteInterface::PALETTE_GRAYSCALE => \Imagick::IMGTYPE_GRAYSCALEMATTE,
        );
 
        if (!isset(static::$colorspaceMapping[$palette->name()])) {
            throw new InvalidArgumentException(sprintf('The palette %s is not supported by Imagick driver', $palette->name()));
        }
 
        $this->imagick->setType($typeMapping[$palette->name()]);
        $this->imagick->setColorspace(static::$colorspaceMapping[$palette->name()]);
        $this->palette = $palette;
    }

I think, that \Imagick::IMGTYPE_TRUECOLOR instead should be a reliable solution.

**Comment by burzum** [comment]
Are you using the develop branch or 6.3.x?

**Comment by kvbogdanov** [comment]
Only stable versions:

Imagine - v0.6.3
ImageMagick -7.0.4-5 Q16 x86_64

**Comment by masterix21** [comment]
i have the same issue using "imagine/imagine": "^0.6.3".

Any ideas?

**Comment by exa18** [comment]
@masterix21 perferct solution, thanky you
this file is: .../concrete/vendor/imagine/imagine/lib/Imagine/Imagick
> Image.php

**Comment by carlos22** [comment]
Is this fixed in newer versions? A proper fix might check if that constant exists?
