### ISSUE TITLE
Call to undefined method Imagick::setImageOpacity()

### ISSUE THREAD

**Issue by kwojc** [avalanche123/Imagine#539]
Hi guys,
on my development env I'm getting `Call to undefined method Imagick::setImageOpacity()` in create method in Imagine class. My version of Imagick:
`
  'versionNumber' =>
  int(1796)
  'versionString' =>
  string(68) "ImageMagick 7.0.4-7 Q16 x86_64 2017-02-04 http://www.imagemagick.org"
`

On production we have a 6.8 version and it works properly :)

**Comment by trsteel88** [comment]
Having the same problem.

**Comment by 3D-I** [comment]
May be related?
https://github.com/avalanche123/Imagine/pull/547#issuecomment-297634632
