### ISSUE TITLE
file_get_contents is disabled on my server i can use curl ?

### ISSUE THREAD

**Issue by khalidahmada** [avalanche123/Imagine#548]
Can i use Curl insted of file_get_contents ?

**Comment by robfrawley** [comment]
The short answer is no, currently [multiple components](https://github.com/avalanche123/Imagine/search?utf8=%E2%9C%93&q=file_get_contents) implement direct calls to `file_get_contents`.

You could possibly write a PR that abstracts all file operations and provides different concrete implementation. At the very least you'd need one implementation equivalent to the current operations. Any PR would need to implement reliant tests and be of high quality for it to be considered; no guarantee such a PR would be accepted, though.

IMHO, the more appropriate response is to drop whatever shared service provide made the horrible decision to remove one of the more secure mechanisms of reading in contents available in PHP. Look elsewhere, as they obviously don't have a firm grasp on reality.

**Comment by khalidahmada** [comment]
Thank you @robfrawley I will do
