### ISSUE TITLE
exif_read_data(39138_JAS-01535-7.jpg): Incorrect APP1 Exif Identifier Code;

### ISSUE THREAD

**Issue by mrrrrt** [avalanche123/Imagine#562]
Hello! After proceeding 2000 images via your lib (to make thumbnails), i looked to log file and descovered 1000 + strings with messages like this "exif_read_data(39138_JAS-01535-7.jpg): Incorrect APP1 Exif Identifier Code;" or "exif_read_data(33477_t3-racer-midwest-sirona-germaniya-a15730-600x600.png): File not supported;";
Problem came from vendor\imagine\imagine\lib\Imagine\Image\Metadata\ExifMetadataReader.php string 97.
`if (false === $exifData = @exif_read_data($path, null, true, false)) {
       return array();
}`

I got Imagine via Composer. Did i do something wrong?

**Comment by robfrawley** [comment]
Those error messages are coming from the call to `exif_read_data` when it is passed incompatible files (anything not `jpeg`, really), though the `@` should silence any errors thrown from the function.

**Comment by Mateil** [comment]
I use custom error handler that made by me. And I discovered the key of my problem. When I use set_error_handler I should use (if (error reporting ()) {...}.) In case if we use @ error_reporting returns 0. 
I'm newbie so forgive me for it and for my English.
Thanks for answer

**Comment by mlocati** [comment]
Fixed by #620
