### ISSUE TITLE
[ExifMetadataReader] Omitted metadata sources such as GPS

### ISSUE THREAD

**Issue by dkarlovi** [avalanche123/Imagine#568]
Currently, [`ExifMetadataReader` reads from `EXIF`, `IFD0`](https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Image/Metadata/ExifMetadataReader.php#L102).

But, [exif_read_data](http://php.net/manual/en/function.exif-read-data.php) provides: `FILE`, `COMPUTED`, `IFD0`, `THUMBNAIL`, `EXIF`, `GPS`, `INTEROP` and probably others. This means those other metadata sources end up being ignored (which is a problem for me as I was trying to figure out why GPS wasn't getting read properly).

You should probably allow for additional metadata sources here or at least allow for specifying sources in the constructor.

**Comment by robfrawley** [comment]
I'd be happy to review a PR! :-)

**Comment by dkarlovi** [comment]
@robfrawley fair enough, I'll send something during the week. :)
