### ISSUE TITLE
Rotating PNG files

### ISSUE THREAD

**Issue by pengend** [avalanche123/Imagine#570]
Hello,

I tried to rotate an PNG file with transparent area using GD driver, and the area becomes black after the rotation. Then I read several posts about this issue, apparently some image manipulation functions must be executed before the rotation to keep the image transparency, but this is not done in the method of the class Imagine\Gd\Image, unless we add other options like crop, resize etc.

More detail on [this issue](https://github.com/liip/LiipImagineBundle/issues/964) that I reported by mistake.

**Comment by robfrawley** [comment]
Here's the explanation about this issue from @pengend in liip/LiipImagineBundle#964:

> The private method createImage of the class Imagine\Gd\Imagegenerates a image ressource which already allows manipulation with PNG image transparency.
> 
> ```php
> $transparent = imagecolorallocatealpha($resource, 255, 255, 255, 127);
> imagefill($resource, 0, 0, $transparent);
> imagecolortransparent($resource, $transparent);
> ```
>
> If this method is not called, the property resource Imagine\Gd\Image does not consider the file like PNG files, and manipulates it like a JPEG one.
> 
> The problem is this method is used only in copy, crop, resize, slip methods, and NOT IN rotate, that's why the transparency is not kept when we call only rotate method.

**Comment by mlocati** [comment]
See https://github.com/avalanche123/Imagine/pull/593#issuecomment-414730784 for a sample code that can rotate an image and set the transparent background.
