### ISSUE TITLE
Rotate img / EXIF Orientation: Rotate 90 CW

### ISSUE THREAD

**Issue by Oliv-** [avalanche123/Imagine#575]
hello, 
the thumbnails of some images are rotate (vertical to horiz.). Do I forget something?...
Pic : iPhone6 with _EXIF Orientation: Rotate 90 CW_.
Thanks

**Comment by pbowyer** [comment]
@Oliv- can you provide a sample image file and your PHP version? I've seen mixed results with different iPhones, and don't have the 6 to hand.

**Comment by mlocati** [comment]
I'm closing this issue because it lacks the necessary details to be inspected (e.g. a sample file as requested by @pbowyer).
But feel absolutely free to reopen it (but please provide a sample image).
