### ISSUE TITLE
thumbnail not support  width 290px  height scale?

### ISSUE THREAD

**Issue by nathanwang** [avalanche123/Imagine#586]
$imagine = new Imagine();
            $image = $imagine->open($originPath);
            $size = new Box(290, 290);
            $mode = ImageInterface::THUMBNAIL_INSET;
            $thumbPath = $saveDir . $thumbName . '.' . $this->file->extension;
            $image->thumbnail($size, $mode)->save($thumbPath); //缩略图

**Comment by robfrawley** [comment]
Can you please describe the exception or issue you have encountered?

**Comment by mlocati** [comment]
Please reopen this issue of its still the case (but please add a description of the problem).
