### ISSUE TITLE
exif_read_data had changed warning to throw exception

### ISSUE THREAD

**Issue by gouchaoer** [avalanche123/Imagine#592]
in `if (false === $exifData = @exif_read_data($path, null, true, false)) {`, 
the function `exif_read_data` had changed, but the php.net doc is not updated.

php7.2's break BC ****** me so much

**Comment by robfrawley** [comment]
@gouchaoer Please avoid using strong language. I've edited your comment to remove such.

**Comment by lentex** [comment]
Hey, I do have the exact same problem. Is there any intention that this behaviour will be changed? Could the `extract` method just catch the `exif_read_data`-Exception and in this case return an empty array?

**Comment by lentex** [comment]
see #598

**Comment by mlocati** [comment]
Fixed by #598
