### ISSUE TITLE
给帽子改变颜色

### ISSUE THREAD

**Issue by yinwanjin** [avalanche123/Imagine#596]
![image](https://user-images.githubusercontent.com/25823112/41211784-3a1e6bf0-6d6c-11e8-9730-8c7fdf280248.png)

下面是我的代码
    ```
           $imagine = new Imagine();
		$image = $imagine->open('static/img/320T/320T_FINAL.png');
		$pink = $image->palette()->color(array(255, 0, 0), 100); 
		$image->effects()
		// ->sharpen()
		// ->gamma(1.3)
		->colorize($pink);
		header('Content-type: image/jpeg');
		echo $image;exit;
```
直接改变颜色，颜色不够真实，并且职能给黑色的图片上色，给其他颜色的图片上色，例如红色，
$pink = $image->palette()->color('#e7135a');
生成的图片颜色，不对。

问题：
1、生成的图片没有原图真实
2、生成颜色不对

**Comment by mlocati** [comment]
Please submit issues in English...
