### ISSUE TITLE
Add Mlocati as a new maintainer

### ISSUE THREAD

**Issue by KorvinSzanto** [avalanche123/Imagine#603]
Semi-recently, there has been concern over whether this project is still alive: #521 and we've been discussing potentially forking in order to get the security / functionality fixes we need merged. Instead of doing that, I'd like to nominate @mlocati to be included as a maintainer of Imagine.

If you take a look at @mlocati's github account you'll see that he is an open source veteran and a consistent contributor to all sorts of projects including this one. He has several pull requests open at the moment:

- #585 
- #584
- #583
- #580
- #495

and so he has demonstrated a deep understanding of how this library functions, at least in-so-far as these fixes / changes have required. I'd argue that @mlocati is the ideal addition to the maintainer team and will help keep Imagine alive and kicking into the future.

**Comment by avalanche123** [comment]
this sounds good to me, I'll let @romainneutron, @burzum, @thePanz or @robfrawley object, if I don't hear objections before then, I'll add @mlocati as a contributor to the repository early next week

**Comment by avalanche123** [comment]
done

**Comment by mlocati** [comment]
@avalanche123 Thank you.

I've just a couple of questions:
- about making decisions about something: should I first ask the other maintainers?
- should the `master` branch point to the latest release?

**Comment by avalanche123** [comment]
Always a good idea to ask for feedback before making a decision, but set a time cap on it, this way all interested parties have a time to respond and you can make progress if that doesn’t happen. Master is the stable branch, some times it matches the latest a release, usually it is a bit ahead

**Comment by mlocati** [comment]
> Always a good idea to ask for feedback before making a decision, but set a time cap on it, this way all interested parties have a time to respond and you can make progress if that doesn’t happen.

:+1:

> Master is the stable branch, some times it matches the latest a release, usually it is a bit ahead

So, at the moment `master` needs to be fast-forwarded, right? It's still at a commit of 2014-08-26, whereas last version (which should be considered stable) is dated 2017-05-16...

**Comment by mlocati** [comment]
> Always a good idea to ask for feedback before making a decision, but set a time cap on it, this way all interested parties have a time to respond and you can make progress if that doesn’t happen.

I'll wait a 3/4 days before merging my own new pull requests (if they are not just decorative ones).

About existing pull requests: if they don't have any kind of downvote from any of the people that have write access (@avalanche123, @burzum, @jmikola, @robfrawley, @romainneutron, @thePanz) I'll merge them (of course, if they seems ok to me :wink:).

**Comment by avalanche123** [comment]
Sounds good to me, thanks for the heads up!

**Comment by mlocati** [comment]
@avalanche123 For #614 I'd need https://github.com/avalanche123/Imagine/pull/614#issuecomment-414302497

**Comment by mlocati** [comment]
@avalanche123 how's the process to publish the docs and API to imagine.readthedocs.io ?
