### ISSUE TITLE
Image being cropped when resized proportionally

### ISSUE THREAD

**Issue by edgarciametro** [avalanche123/Imagine#621]
We start with a 2175x2175 image, then we request it to be resized to 1040x1040. We get the 1040x1040 as expected, but the original image is cropped about ~8% first, then it is resized. How can we prevent the crop from happening?

Original image:
https://storage.googleapis.com/pyp-dev/cs/files/244393/original/NUY3yNAfTHGejeg4RLGXs3eKukzZZS6yjpJRhrHQ.png

Resized image: 
https://storage.googleapis.com/pyp-dev/cs/files/244393/preview/NUY3yNAfTHGejeg4RLGXs3eKukzZZS6yjpJRhrHQ.png

```
$this->hasAttachedFile('file', [
            'styles' => array_merge(static::$thumbStyles, [
                'preview' => [
                    'dimensions' => '1040x1040',
                    'auto_orient' => true,
                    'convert_options' => [
                        'format' => 'png',
                        'png_compression_level' => 9,
                        'png_compression_filter' => PNG_FILTER_NONE
                    ]
                ]
            ])
        ]);
```

**Comment by mlocati** [comment]
Do you have the PHP code that resizes the image?

**Comment by edgarciametro** [comment]
In the first is what I think does the resizing.

**Comment by mlocati** [comment]
You just posted the links of two images, and a chunk of PHP code which I think is using another library (`$this->hasAttachedFile` is not part of Imagine)

**Comment by edgarciametro** [comment]
Apologies, this is from CodeSleeve’s Stapler (Which uses Imagine), and the code above runs this from Imagine.

`$image->resize(new Box($width, $height));`

**Comment by edgarciametro** [comment]
Sorry we found out that their code does changes to the way the Imagine resize works. This issue is not about Imagine.

**Comment by mlocati** [comment]
No problems at all, don't worry
