### ISSUE TITLE
supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by crocone** [avalanche123/Imagine#696]
$new_image does not exist.
Because it is created from the old file. (image)

`Image::frame($image, 5, '666', 0)->rotate(-8)->save($new_image, ['jpeg_quality' => 50]);`

Error: 
PHP Warning 'yii\base\ErrorException' with message 'stream_get_contents(): supplied resource is not a valid stream resource' 

in /*************/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:119

**Comment by mlocati** [comment]
You are using an old Imagine version. Please report issues only for the most recent version.

**Comment by crocone** [comment]
Im using 1.1.0 imagine version 
But error stayed
PHP Warning 'yii\base\ErrorException' with message 'stream_get_contents(): supplied resource is not a valid stream resource' 

in /*********l/vendor/imagine/imagine/src/Gd/Imagine.php:119

**Comment by mlocati** [comment]
When you submitted this issue, you should have been presented [this set of questions](https://github.com/avalanche123/Imagine/blob/develop/.github/ISSUE_TEMPLATE.md).
Those questions are there for a reason: I need to be able to replicate your error using only Imagine code.
Indeed, when you report the sample code
```php
Image::frame($image, 5, '666', 0)
```
I don't know what's `Image::frame` (it's not part of Imagine - it seems code from another library), and I don't know what `$image` contains.
So, I really can't help you.
