### ISSUE TITLE
Installation fails: The requested package imagine/imagine No version set (parsed as 1.0.0) is satisfiable by imagine/imagine[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

### ISSUE THREAD

**Issue by pchepali** [avalanche123/Imagine#703]
Hello guys,
need your help on this please:
when trying to install composer.json as per the README file (composer require imagine/imagine:~1.2.0 or composer require imagine/imagine) it fails:
"./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package imagine/imagine No version set (parsed as 1.0.0) is satisfiable by imagine/imagine[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
Installation failed, reverting ./composer.json to its original content."

PHP 7.0.32- Ubuntu
Imagine v1.2.0
Extra: I did try it to run it (composer.json) within the extracted tar.gz and even outside; same result.
Thank you!
Pablo

**Comment by pchepali** [comment]
Composer version 1.8.3
Looking forward to your help.

**Comment by mlocati** [comment]
Could you share the listing of the content of your working directory and the exact command you are typing?

**Comment by pchepali** [comment]
Hello Michele,

I have download it from here: https://github.com/avalanche123/Imagine/releases (v1.2.0)

Directory structure:

src/
CHANGELOG.md
composer.json
LICENSE
README.md

all owned by www-data.

The command is (composer.phar runs as composer): composer require imagine/imagine  

Thank you for your help!

Pablo



    On Wednesday, February 6, 2019, 8:41:02 AM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
Could you share the listing of the content of your working directory and the exact command you are typing?

**Comment by mlocati** [comment]
You don't have to download the project manually: composer will do that for you.
Starting from scratch (that is, on an empty dir), just type these commands:

```sh
# Create an empty composer.json file
echo {} > composer.json
# Let composer download Imagine
composer require imagine/imagine
```

then, to use Imagine in your PHP files, simply start with:
```php
<?php
require_once './vendor/autoload.php';
```

**Comment by pchepali** [comment]
Thank you Michele!
Will try it later at night and let you know.
Regards,Pablo

    On Wednesday, February 6, 2019, 3:11:03 PM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
You don't have to download the project manually: composer will do that for you.
Starting from scratch (that is, on an empty dir), just type these commands:
# Create an empty composer.json file
echo {} > composer.json
# Let composer download Imagine
composer require imagine/imagine
then, to use Imagine in your PHP files, simply start with:
<?php
require_once './vendor/autoload.php';

**Comment by pchepali** [comment]
Thank you Michele,
the structure was created but at the time to instance the class it throws:
PHP Fatal error:  Uncaught Error: Class 'Image\Gd\Imagine' not found in /var/www/domain/genImages.php:10

code:<?php
require_once 'vendor/autoload.php';
        echo "genImages.test::00";
        $imagine =  new Image\Gd\Imagine();
        echo "genImages.test::01";?>

The directory structure:
-rw-r--r-- 1 www-data  www-data  178 Feb  6 23:49 autoload.php
drwxrwxr-x 2 www-data  www-data 4.0K Feb  6 23:49 composer
drwxrwxr-x 3 www-data  www-data 4.0K Feb  6 23:48 imagine

Thank you for your help!Pablo
    On Wednesday, February 6, 2019, 3:11:03 PM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
You don't have to download the project manually: composer will do that for you.
Starting from scratch (that is, on an empty dir), just type these commands:
# Create an empty composer.json file
echo {} > composer.json
# Let composer download Imagine
composer require imagine/imagine
then, to use Imagine in your PHP files, simply start with:
<?php
require_once './vendor/autoload.php';

**Comment by mlocati** [comment]
The actual name of the `Imagine` class for the Gd driver is `Imagine\Gd\Imagine` and not `Image\Gd\Imagine` (see [here](https://github.com/avalanche123/Imagine/blob/1.2.0/src/Gd/Imagine.php#L12)).

Here's a sample session:

```sh
$ echo {} > composer.json

$ composer require imagine/imagine
Using version ^1.2 for imagine/imagine
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing imagine/imagine (1.2.0): Loading from cache
Writing lock file
Generating autoload files

$ cat <<'EOT' > test.php
<?php
require_once 'vendor/autoload.php';
echo "genImages.test::00";
$imagine = new Imagine\Gd\Imagine();
echo "genImages.test::01";
EOT

$ ls -l
total 4
-rwxrwxrwx 1 m m   61 Feb  7 10:53 composer.json
-rwxrwxrwx 1 m m 2603 Feb  7 10:53 composer.lock
-rwxrwxrwx 1 m m  133 Feb  7 10:53 test.php
drwxrwxrwx 1 m m  512 Feb  7 10:53 vendor

$ php test.php
genImages.test::00genImages.test::01
```

**Comment by pchepali** [comment]
Sorry for the silly issue; is working. But this:
 new Imagine\Image\Color('fff', 0)
triggers:Fatal error: Uncaught Error: Class 'Imagine\Image\Color' not found in

this call is in the same file as new Imagine\Gd\Imagine (an not exception):
 $imagine =  new Imagine\Gd\Imagine();
        echo "genImages.transparent_back1";
        $imagine->open($filename)
        ->save(_TRANSPARENT_PRE . $filename,new Imagine\Image\Color('fff', 0));

https://imagine.readthedocs.io/en/v0.2.4/api/Image/Color.html
Thanks a lot Michele!
    On Wednesday, February 6, 2019, 3:27:00 PM GMT+1, Pablo Chepalich <pchepalich@yahoo.com> wrote:  
 
  Thank you Michele!
Will try it later at night and let you know.
Regards,Pablo

    On Wednesday, February 6, 2019, 3:11:03 PM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
You don't have to download the project manually: composer will do that for you.
Starting from scratch (that is, on an empty dir), just type these commands:
# Create an empty composer.json file
echo {} > composer.json
# Let composer download Imagine
composer require imagine/imagine
then, to use Imagine in your PHP files, simply start with:
<?php
require_once './vendor/autoload.php';

**Comment by mlocati** [comment]
https://imagine.readthedocs.io/en/v0.2.4/api/Image/Color.html is for a really old Imagine version.
The updated API docs are located at https://imagine.readthedocs.io/en/stable/_static/API/

**Comment by pchepali** [comment]
Hello Michele,
thank you for your support; why the images is created without a transparent background??
$image = $imagine->open($filename);
        echo "image.Mgmt.transp2 = " . _TRANSPARENT_EXT;
//      error_log("imageMgmt.transp2=", 0);
        $palette = new Imagine\Image\Palette\RGB();
        $palette->color('fff', 0); //same with 100
        $image->usePalette($palette);

?????The image has already a white background (always); so I want to eliminate it.

Thank you again!Pablo
    On Thursday, February 7, 2019, 8:45:29 PM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
https://imagine.readthedocs.io/en/v0.2.4/api/Image/Color.html is for a really old Imagine version.
The updated API docs are located at https://imagine.readthedocs.io/en/stable/_static/API/

**Comment by pchepali** [comment]
Hello Michele,
Yes, as you say. The image has a white background and I would like to remove it (make it transparent). Above code is doing nothin in the image.

Sorry I didn't express properly.

    On Friday, February 15, 2019, 7:22:11 AM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
I'm sorry I don't understand what you are asking...
Are you loading an image with a white background and you would like to replace this white background with transparency?

**Comment by pchepali** [comment]
Hello Michele,
I'm following the documentation/examples and the image still keeps the white background.Quick introduction — Imagine, image manipulations reloaded

| 
| 
|  | 
Quick introduction — Imagine, image manipulations reloaded


 |

 |

 |




The image always has a white background to make it transparent.
Looking forward to your help.
Thank you!Pablo

    On Friday, February 15, 2019, 9:42:45 AM GMT+1, Pablo Chepalich <pchepalich@yahoo.com> wrote:  
 
  Hello Michele,
Yes, as you say. The image has a white background and I would like to remove it (make it transparent). Above code is doing nothin in the image.

Sorry I didn't express properly.

    On Friday, February 15, 2019, 7:22:11 AM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
I'm sorry I don't understand what you are asking...
Are you loading an image with a white background and you would like to replace this white background with transparency?

**Comment by mlocati** [comment]
I'm not aware of an Imagine-specific method that can be used to replace a color (white in your case) with transparency.

**Comment by pchepali** [comment]
Thank you Michele and sorry for the late response.
Quickone:why I'm getting an error in this function:img_main(.png) and img_child (.gif) exist 

function animate($duration,$img_main,$img_child,$loops){
        echo "genImages.animate::00";
        $imagine =  new Imagine\Gd\Imagine();
        echo "genImages.animate::01";
        $img_main = $imagine->open($img_main);
        $resize_img = $imagine->open($img_child);
        $resize_img = resize($resize_img,$img_main->getSize()->getWidth(),$img_main->getSize()->getHeight());
        $img_main->layers()->add($resize_img);
        $img_main->layers()->add($img_main); 

        $imagine->save($img_child . "an.gif", array('animated' => true,$duration,$loops));
        return $img_child . "an.gif";
}


Fatal error: Uncaught Imagine\Exception\NotSupportedException: GD does not support layer set in /var/www/test/lib/vendor/imagine/imagine/src/Gd/Layers.php:183Stack trace:#0 /var/www/test/lib/vendor/imagine/imagine/src/Image/AbstractLayers.php(32): Imagine\Gd\Layers->offsetSet(NULL, Object(Imagine\Gd\Image))

Question, how can I set the duration of each image in the total animated duration?
Thank you!
    On Friday, February 15, 2019, 11:25:51 PM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
I'm not aware of an Imagine-specific method that can be used to replace a color (white in your case) with transparency.

**Comment by mlocati** [comment]
As described in the error message, the cause is that GD doesn't support layers/frames.
You should switch to Imagick

**Comment by pchepali** [comment]
Thank you Michele!!
What I can't find in your documentation is a way to set how long last each image in the sequence:
https://imagine.readthedocs.io/en/stable/usage/layers.html  (Also, duration in the array of parameter when saving is the whole animated gif duration?) 

https://stackoverflow.com/questions/9417762/make-an-animated-gif-with-phps-imagemagick-api
Thank you again!



    On Saturday, February 23, 2019, 10:21:22 AM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
As described in the error message, the cause is that GD doesn't support layers/frames.
You should switch to Imagick

**Comment by pchepali** [comment]
Hello Michele,
the animated gif is made of a gif (animated) and png
at the time I apply the duration translated in your src:($layer->getImagick()->setImageDelay($delay / 10);$layer->getImagick()->setImageTicksPerSecond(100);) it's only applied to the gif and not also to the png.
What can I do?
So the idea is: in (png and gif/png), out .gif animated which each of the layers are shown after x seconds.
Thanks a lot and sorry to bother you!

    On Saturday, February 23, 2019, 12:30:04 PM GMT+1, Pablo Chepalich <pchepalich@yahoo.com> wrote:  
 
  Thank you Michele!!
What I can't find in your documentation is a way to set how long last each image in the sequence:
https://imagine.readthedocs.io/en/stable/usage/layers.html  (Also, duration in the array of parameter when saving is the whole animated gif duration?) 

https://stackoverflow.com/questions/9417762/make-an-animated-gif-with-phps-imagemagick-api
Thank you again!



    On Saturday, February 23, 2019, 10:21:22 AM GMT+1, Michele Locati <notifications@github.com> wrote:  
 
 
As described in the error message, the cause is that GD doesn't support layers/frames.
You should switch to Imagick

**Comment by mlocati** [comment]
There's no a per-frame setting for the duration. See also https://github.com/avalanche123/Imagine/issues/506
