### ISSUE TITLE
Unable to work with pecl 3.4.4 and ImageMagick 6

### ISSUE THREAD

**Issue by samdark** [avalanche123/Imagine#715]
### Issue description

`\Imagick::setImageOpacity()` was deprecated in PECL extension version 3.4.4 and `\Imagick::setImageAlpha()` is not there before ImageMagick 7. [In this case](https://github.com/avalanche123/Imagine/blob/19a5897b672940b6b2e77fd6ddf04f6535abc912/src/Imagick/Imagine.php#L104) it fails with "Function Imagick::setimageopacity() is deprecated":

```php
if (version_compare('6.3.1', $this->getVersion($imagick)) < 0) { // <-- using 6.7.7, passes
    // setImageOpacity was replaced with setImageAlpha in php-imagick v3.4.3
    if (method_exists($imagick, 'setImageAlpha')) { // <-- does not exist before 7.x.x
        $imagick->setImageAlpha($pixel->getColorValue(\Imagick::COLOR_ALPHA));
    } else {
        $imagick->setImageOpacity($pixel->getColorValue(\Imagick::COLOR_ALPHA));
        // ^ throws deprecation error with PECL 3.4.4
    }
}
```
### What version of Imagine are you using?

1.2.1-dev

### What's the PHP version you are using?

Any.

### What's the imaging library you are using [gd/imagick/gmagick/any]?

- ImageMagick 6.7.7-10 2017-07-31 Q16
- PECL extension version 3.4.4

### What's the imaging library configuration 

Does not matter.

### Minimal PHP code to reproduce the error: 

```php
$imagine = new \Imagine\Imagick\Imagine();
$color = (new RGB())->color('FFF', 10);
$image = $imagine->create(new Box(100, 100), $color);
```

**Comment by samdark** [comment]
https://github.com/Imagick/imagick/issues/288

**Comment by Danack** [comment]
Fyi:

i) there were other methods that were deprecated also: https://pecl.php.net/package-changelog.php?package=imagick

ii) It is planned that this is the last version (other than security fixes) of Imagick that will support ImageMagick 6. Yeah I'm aware that this is going to be mildly annoying for some users.
