### ISSUE TITLE
Optimizing Image Resizing

### ISSUE THREAD

**Issue by crimson-med** [avalanche123/Imagine#722]
### Issue description

Got an error upon resizing images that the server memory was not sufficient enough.

I upload a JPG image of 1.6M of size: 2880x1620 and trying to resize it to: 1920x1080.

This process works but consumes over 140M of memory allocation

...

### What version of Imagine are you using?

1.2.2

### What's the PHP version you are using?

PHP 7.1.17

### What's the imaging library you are using [gd/imagick/gmagick/any]?

gd

### What's the imaging library configuration 

```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.3.11
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 6b
PNG Support => enabled
libPNG Version => 1.2.49
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

### Minimal PHP code to reproduce the error: 

```php
    private function resizeImage($path, $pathSave, $width, $height, $quality = 80) {
        $imagine = new \Imagine\Gd\Imagine();
        $imageI = $imagine->open($path);
        $sizeI = $imageI->getSize();
        $wI = $sizeI->getWidth();
        $hI = $sizeI->getHeight();
        $ratio = ($hI == 0) ? 1.0 : $wI/$hI;
        // don't enlarge
        if (($wI <= $width) && ($hI <= $height)) {
            // just forget about resizing, image is smaller than required frame
            return false;
        }
        // if you want an image that is always square comment this
        // keep w and h ints
        if ($ratio > 1.0) {
            // keep w - resize h
            $height = ceil($width / $ratio);
        } else {
            // resize w - keep h
            $width = ceil($height * $ratio);
        }
        $size = new \Imagine\Image\Box($width, $height);
        // resized image based on requested w x h
        $imageR = $imageI->thumbnail($size, \Imagine\Image\ImageInterface::THUMBNAIL_INSET);
        $sizeR = $imageR->getSize();
        $wR = $sizeR->getWidth();
        $hR = $sizeR->getHeight();
        // reposition
        $image = $imagine->create($size);
        $x = ($wR < $width) ? floor(0.5 * ($width - $wR)) : 0;
        $y = ($hR < $height) ? floor(0.5 * ($height - $hR)) : 0;
        $image->paste($imageR, new \Imagine\Image\Point($x, $y))
            ->save($pathSave, ['quality' => $quality]);
        return true;
    }

```

**Comment by mlocati** [comment]
> I upload a JPG image of 1.6M of size: 2880x1620

The file size is very little relevant when working with images.
What matters is the image size in pixels.

You can try to reduce the memory usage by using the "in-place" resizing, by adding ` | \Imagine\Image\ImageInterface::THUMBNAIL_FLAG_NOCLONE` to the thumbnail method.
This will change the `$imageI` instance directly, so you won't need the `$imageR` instance.

Furthermore, in addition to `$imageI` and `$imageR`, you also create a 3rd image (`$image`). Why? Keep in mind that every image requires (a lot) of memory: that's not an Imagine issue, it's simply the way that GD/Imagick/Gmagick libraries work (they keep the images in memory for faster processing).

That's all I can suggest...
