### ISSUE TITLE
Serve image with filename using $image->show(…);

### ISSUE THREAD

**Issue by piaaaac** [avalanche123/Imagine#739]
What I want to accomplish is very simple: add an image name to the served image. I made a simple script named `thumbs.php` that uses Imagine to create the thumbnail with a unique name into a `thumbs` folder and serves it using $image->show('jpg'). If the thumb has already been generated the file is used directly from the thumbs folder.

`thumbs.php` looks like this
```php
require_once "../config.php";
require_once path("vendor") ."/autoload.php";
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Imagine\Gd\Imagine;
$imagine = new Imagine();

// --- Check inputs
if (!isset($_GET["path"])) {
	die("Error: no path provided (89754698)");
} elseif (!startsWith(urldecode($_GET["path"]), "content/")) {
	die("Error: path needs to start with 'content/' (98758964)");
}
if (!isset($_GET["w"]) && !isset($_GET["h"])) {
	die("Error: either 'w' or 'h' must be provided (98765342)");
}
if (isset($_GET["q"]) && !is_numeric($_GET["q"])) {
	die("Error: non numeric 'q' provided (83976598)");
} else {
	$q = (isset($_GET["q"])) ? (int)$_GET["q"] : 80;
}

// --- Check if thumb exists
$imagePath = path("site") ."/". urldecode($_GET["path"]);
$cleanName = substr($imagePath, strlen(path("content")) + 1);
$sizeSuffix = isset($_GET["w"]) ? ("w". $_GET["w"]) : ("h". $_GET["h"]);
$outputPath = path("thumbs") ."/". slugify($cleanName. "-q". $q ."-". $sizeSuffix) .".jpg";
if (file_exists($outputPath)) {
	$image = $imagine->open($outputPath);
	$image->show('jpg'); // <<<<<<<<<< add filename?
	exit;
} 

// --- Create and serve thumb
$image = $imagine->open($imagePath);
$w = $image->getSize()->getWidth();
$h = $image->getSize()->getHeight();
if (isset($_GET["w"])) {
	$newW = $_GET["w"];
	$newH = round($h/$w * $newW);
} else {
	$newH = $_GET["h"];
	$newW = round($w/$h * $newH);
}
$image->resize(new Box($newW, $newH));
$image->save($outputPath, ['jpeg_quality' => $q]);
$image->show('jpg'); // <<<<<<<<<< add filename?

```

Right now all the images are called thumbs.jpg and I think the browser can't cache them.
Is this possible? I browsed the docs carefully and didn't find anything.

Additional info
- Imagine v1.2.3 added using composer
- PHP 7.3.11 (7.2 on production server)
- imaging library: GD bundled (2.1.0 compatible)

**Comment by mlocati** [comment]
The browser may cache images not by "name" (whatever you mean with that), but by its URL.
So, you should have an unique URL for every image, and play with HTTP headers to tell the browser to cache the returned  image.

**Comment by piaaaac** [comment]
Thanks for your answer.
By "name" I mean the filename I see when I download the generated image.

> you should have an unique URL for every image, and play with HTTP headers to tell the browser to cache the returned image

Could you point me in the right direction to do that?

**Comment by mlocati** [comment]
> By "name" I mean the filename I see when I download the generated image.

You could try to use the [`Content-Disposition` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), something like this (before sending the image to the client):

```php
header('Content-Disposition: inline; filename="wonderful-image-name.jpg"');
```

> Could you point me in the right direction to do that?

Sure! See [here](https://lmgtfy.com/?q=php+headers+cache) :wink:

**Comment by piaaaac** [comment]
😅 really?

> You could try to use the Content-Disposition header, something like this (before sending the image to the client)

Thanks

**Comment by piaaaac** [comment]
Is there a way to add a header to the one sent by `$image->show()` or do I have to send the image manually?

```
// from src/Gd/Image.php
public function show($format, array $options = array())
{
    header('Content-type: ' . $this->getMimeType($format));
    // additional 'Content-Disposition' header here <<<<

    $this->saveOrOutput($format, $options);

    return $this;
}
```

Or, looking at the code of `saveOrOutput()` I wonder if there's a way to add the filename (that would correspond to the 3rd parameter) when it's executed by `$image->show()`, which was my original intention.

```
private function saveOrOutput($format, array $options, $filename = null)
{
    $format = $this->normalizeFormat($format);
    // ...
```

**Comment by mlocati** [comment]
That would overcomplicated the code... which disposition, inline or attachment? What if the file name is not available, or the original file has a jpg extension but you are serving a png file...
The easiest solution is to add headers on your own
