### ISSUE TITLE
Server crashes while opening EPS files using Imagick

### ISSUE THREAD

**Issue by msrumon** [avalanche123/Imagine#753]
### Issue description

When I try to open *EPS* files using **Imagick** extension, the server crashes.

### What version of Imagine are you using?

1.2.4

### What's the PHP version you are using?

```bash
$ php -v
PHP 7.4.13 (cli) (built: Nov 24 2020 12:43:30) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

### What's the imaging library you are using [gd/imagick/gmagick/any]?

imagick

### What's the imaging library configuration 

```bash
$ php --ri imagick

imagick

imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.0.7-11 Q16 x64 2017-11-23 http://www.imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.0.7-11 Q16 x64 2017-11-23 http://www.imagemagick.org
ImageMagick copyright => Copyright (C) 1999-2015 ImageMagick Studio LLC
ImageMagick release date => 2017-11-23
ImageMagick number of supported formats:  => 238
ImageMagick supported formats => 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CLIPBOARD, CMYK, CMYKA, CR2, CRW, CUR, CUT, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPS, DPX, DXT1, DXT
5, EMF, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLIF, FPX, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, IS
OBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO
, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA,
RLE, RMF, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WPG, X3F, XBM,
 XC, XCF, XPM, XPS, XV, YCbCr, YCbCrA, YUV

Directive => Local Value => Master Value
imagick.locale_fix => 0 => 0
imagick.skip_version_check => 0 => 0
imagick.progress_monitor => 0 => 0
```

### Minimal PHP code to reproduce the error: 

Clone [this](https://github.com/msrumon/imagine-imagick-issue) repo.

**Comment by mlocati** [comment]
> the server crashes.

What happens?

**Comment by msrumon** [comment]
Clone the repo I linked > Run `composer i` > Run `php -S localhost:5000` > Open localhost:5000 on browser. You'll see the server has stopped.

**Comment by msrumon** [comment]
I am using this library (v1.2.3) in my Symfony 5 app, and this is what gets logged:
```bash
[Web Server ] Nov 26 21:21:01 |ERROR  | SERVER issue with server callback error="unable to fetch the response from the backend: read tcp 127.0.0.1:2232->127.0.0.1:2057: wsarecv: An existing connection was forcibly closed by the remote host."
[Web Server ] Nov 26 21:21:01 |ERROR  | SERVER POST (502) /dashboard/my-uploads/new host="127.0.0.1:8004" ip="::1" scheme="https"
```
But no error in the linked repo. It just closes the server.

**Comment by mlocati** [comment]
What happens if you simplu run `php index.php`?

**Comment by msrumon** [comment]
No output.

**Comment by mlocati** [comment]
Do you have Ghostscript installed? It's required by the underlying ImageMagick library (used by the imagick PHP extension) to load PDF and EPS files.

**Comment by msrumon** [comment]
I had (v9.52). After you suggestion, I checked for update, found (v9.53.3) and updated it. Now it works. 😄 Thanks. ❤️

**Comment by msrumon** [comment]
One more thing: Can't I open an uploaded file (`.tmp`) directly with this library, before moving it to another location?

**Comment by mlocati** [comment]
IMHO imagick can't understand its type, unless the file has a correct file extension.

**Comment by mlocati** [comment]
BTW, you should ask such questions to the [imagick people](https://github.com/Imagick/imagick), Imagine is "only" a wrapper for graphics libraries (imagick, gd, and gmagick).

**Comment by msrumon** [comment]
Yes I understand. I will play around more to go deeper into it. Thanks again, for giving your valuable time.

**Comment by msrumon** [comment]
@mlocati, I have produced [this problem](https://github.com/avalanche123/Imagine/issues/753#issuecomment-734368442) in the repo I linked above. Can you check it by yourself please?

**Comment by msrumon** [comment]
Opened https://github.com/Imagick/imagick/issues/364. Let's see what they say...
