### ISSUE TITLE
Set font size to 100% of canvas?

### ISSUE THREAD

**Issue by notflip** [avalanche123/Imagine#754]
### Issue description

When creating a new Font() we pass the fontSize (int), I'm wondering if there's a good way to have a text be 100% of the canvas?

### What version of Imagine are you using?

`"imagine/imagine": "^1.2"`

### What's the PHP version you are using?

`PHP 7.4.13 (cli) (built: Nov 27 2020 11:48:14)`

### What's the imaging library you are using [gd/imagick/gmagick/any]?

`Imagick`

### What's the imaging library configuration 

`imagick`

**Comment by ausi** [comment]
You can use the `FontInterface::box()` method to measure how big the text will be at the current size, compare that to the canvas size and adjust the font size accordingly.

**Comment by notflip** [comment]
I'm using a while loop to get the best width or height match but I feel this is not very well in terms of performance.

```
$font = new Font(new \Imagick(), $fontPath, $fontSize, $fontColor);
$textBox = $font->box($text);

while ($textBox->getWidth() > 280 || $textBox->getHeight() > 280) {
	$fontSize--;
	$font = new Font(new \Imagick(), $fontPath, $fontSize, $fontColor);
	$textBox = $font->box($text);
}
```

Was it this you meant by measuring the box?
Thank you.

**Comment by ausi** [comment]
I’d probably use something like this:

```php
$fontSize = 280; // Start with the canvas size

$font = new Font(new \Imagick(), $fontPath, $fontSize, $fontColor);
$textBox = $font->box($text);

// Estimate the correct font size
$fontSize = ceil(280 / (max($textBox->getWidth(), $textBox->getHeight())) * $fontSize) + 1;

while ($textBox->getWidth() > 280 || $textBox->getHeight() > 280) {
	$fontSize--;
	$font = new Font(new \Imagick(), $fontPath, $fontSize, $fontColor);
	$textBox = $font->box($text);
}
```

In most cases this should only take two or three runs through the while loop.

**Comment by ausi** [comment]
@notflip should we close this issuen then? 
I don’t think this specific code should got into the library itself, don’t you think?

**Comment by notflip** [comment]
Of course! It's a just a use case, thanks for your time
