### ISSUE TITLE
Add support for HEIC format

### ISSUE THREAD

**Issue by ninze** [avalanche123/Imagine#755]
Since iphone 11 and up stores images in HEIC format, it would be really nice to support it.

ImageMagick supports HEIC images (needs to be compiled with libheif and libde265).

Imagine fails to open a HEIC file with the following error:

    Only RGB and CMYK colorspace are currently supported

A sample image taken with my iphone 11 says the color space is `YCbCr`. Not sure how difficult it would be to add support for this colorspace and if any other modifications would be required to have HEIC image processing working.

**Comment by ausi** [comment]
Pull request for HEIC support in Imagick driver: #759
