### ISSUE TITLE
An Image Collage Example doesn`t work

### ISSUE THREAD

**Issue by legiero** [avalanche123/Imagine#767]
### Issue description

[An Image Collage](https://imagine.readthedocs.io/en/stable/usage/introduction.html#an-image-collage)

This example does not work. Creates full white image.

### What version of Imagine are you using?

1.2.4

### What's the PHP version you are using?

PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

### What's the imaging library you are using [gd/imagick/gmagick/any]?

gd-2.2.5

### What's the imaging library configuration 

[GD Version] => 2.2.5
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [BMP Support] => 1
    [TGA Read Support] => 1
    [JIS-mapped Japanese Font Support] =>

**Comment by ausi** [comment]
I was unable to reproduce this issue.

Can you post the exact code you used?

Did you replace the `/path/to/people/photos/*.jpg` path from the example with an absolute path to a folder that contains `.jpg` files (lowercase and 3, not 4 letters)?

**Comment by legiero** [comment]
My bad :facepalm:
Mistake in code.
